/// ═══════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: pinky (7661de77-a7d8-48cb-952c-c32d3755fb39)
/// Generated: 2026-04-13T17:20:15.354Z
/// ═══════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'pinky';
  static const String tagline        = '';
  static const String botName        = 'Assistant';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'Hi there! 👋 I\'m **Assistant**, your personal assistant at **pinky**. How can I help you today?';

  static const List<String> quickReplies = [
    '💰 Pricing & Plans',
    '🛠️ Our Services',
    '📞 Contact Support'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#61fcff';
  static const String accentColorHex  = '#ff8566';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://api.botforge.app';
  static const String chatEndpoint   = '/v1/chat';
  static const String organisationId = '7661de77-a7d8-48cb-952c-c32d3755fb39';

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}